# Project: GYM-MFRS
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = gym-membership-and-fitness-management-project.o ../../sqlite-amalgamation-3460000/sqlite-amalgamation-3460000/sqlite3.o
LINKOBJ  = gym-membership-and-fitness-management-project.o ../../sqlite-amalgamation-3460000/sqlite-amalgamation-3460000/sqlite3.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 -L"C:/Program Files/MySQL/MySQL Server 8.0/lib"
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = GYM-MFRS.exe
CXXFLAGS = $(CXXINCS) -Werror
CFLAGS   = $(INCS) -Werror
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

gym-membership-and-fitness-management-project.o: gym-membership-and-fitness-management-project.cpp
	$(CPP) -c gym-membership-and-fitness-management-project.cpp -o gym-membership-and-fitness-management-project.o $(CXXFLAGS)

../../sqlite-amalgamation-3460000/sqlite-amalgamation-3460000/sqlite3.o: ../../sqlite-amalgamation-3460000/sqlite-amalgamation-3460000/sqlite3.c
	$(CC) -c ../../sqlite-amalgamation-3460000/sqlite-amalgamation-3460000/sqlite3.c -o ../../sqlite-amalgamation-3460000/sqlite-amalgamation-3460000/sqlite3.o $(CFLAGS)
